# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install modules
      run: npm install dependecies
    - name: build project bundle
      run: npm run build
    - name: build storybook
      run: npm run build:storybook
    - name: unit tests
      run: npm run test:unit
    - name: e2e tests
      run: npm run test:e2e
    - name: code linting 
      run: npm run linting
    - name: code i18n-checking 
      run: npm run i18n:checking
    - name: code typechecking 
      run: npm run type:checking
